<?php

/* You need to include the path to the CallBack.php here. */
require_once 'path\to\CallBack.php';

/**
 * Generated by PHPUnit_SkeletonGenerator.
 */
class CallBackTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CallBack
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AMpay\CallBack;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ('356ea4adda1e0eae2fb73ce96f59f844','fffff','987698w7e','payment','12345','9147894125','520','233','payment') == true.
     *
     * @covers AMpay\CallBack::checkSign
     */
    public function testCheckSign() {
        $this->assertEquals(
                true
                , $this->object->checkSign('356ea4adda1e0eae2fb73ce96f59f844', 'fffff', '987698w7e', 'payment', '12345', '9147894125', '520', '233', 'payment')
        );
    }

    /**
     * Generated from @assert ('01318be4d94929f3133c74ef3ae4c09d','1536232jkib','987698w7e','payment','12345','9147894125','520','233','payment') == true.
     *
     * @covers AMpay\CallBack::checkSign
     */
    public function testCheckSign2() {
        $this->assertEquals(
                true
                , $this->object->checkSign('01318be4d94929f3133c74ef3ae4c09d', '1536232jkib', '987698w7e', 'payment', '12345', '9147894125', '520', '233', 'payment')
        );
    }

    /**
     * Generated from @assert ('417df99941b7afe2a0bf287197358575','dgs5-dk,lxh7','987698w7e','payment','12345','9147894125','520','233','payment') == true.
     *
     * @covers AMpay\CallBack::checkSign
     */
    public function testCheckSign3() {
        $this->assertEquals(
                true
                , $this->object->checkSign('417df99941b7afe2a0bf287197358575', 'dgs5-dk,lxh7', '987698w7e', 'payment', '12345', '9147894125', '520', '233', 'payment')
        );
    }

   
}
